title: 山水文墨
email: liwenjie2020@ict.ac.cn
description: >-
  学术探索与诗意生活的交汇之地
baseurl: "" # 如部署在子路径下需填写
url: "" # 你的域名

twitter_username: jekyllrb
github_username:  your-github-username

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 自定义古风配置
古风设置:
  主题色:
    主色: "#8B4513"
    辅助色: "#D2B48C"
    文字色: "#3E2723"
  字体:
    标题: "STKaiti, SimKai, serif"
    正文: "STSong, SimSun, serif"
